/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application and Java plugins.
    id("application")
    id("java")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("junit:junit:5.10.2") // Use the latest version


    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    // Adding Pcap4J core library and packet factory.
    implementation("org.pcap4j:pcap4j-core:2.0.0-alpha.6")
    implementation("org.pcap4j:pcap4j-packetfactory-static:2.0.0-alpha.6")
}

application {
    // Define the main class for the application.
    mainClass.set("cw2.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Task to create a fat JAR including all dependencies.
tasks.register("fatJar", Jar::class) {
    archiveBaseName.set("${project.name}-all")
    archiveVersion.set("1.0")
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }
    // Set the duplicate handling strategy
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
    with(tasks.named<Jar>("jar").get())
}

